# EDA for Telco Customer Churn dataset

[dataset link](https://www.kaggle.com/datasets/blastchar/telco-customer-churn)
[dataset description](https://community.ibm.com/community/user/blogs/steven-macko/2019/07/11/telco-customer-churn-1113)

In [17]:
import pandas as pd # pyright: ignore[reportMissingModuleSource]

pd.set_option('display.max_columns', 200)

## Download dataset

In [1]:
%pip install -q kagglehub

In [6]:
# download dataset from kaggle
import kagglehub # pyright: ignore[reportMissingImports]
from pathlib import Path

# Download latest version
path = Path(kagglehub.dataset_download("blastchar/telco-customer-churn"))
path = path / r"WA_Fn-UseC_-Telco-Customer-Churn.csv"

print("Path to dataset files:", path)

Using Colab cache for faster access to the 'telco-customer-churn' dataset.
Path to dataset files: /kaggle/input/telco-customer-churn/WA_Fn-UseC_-Telco-Customer-Churn.csv

In [39]:
df = pd.read_csv(path)
df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,Yes,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,No,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,Yes,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,No,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

## Prelimitary analys

In [12]:
df.shape

(7043, 21)

In [14]:
df.columns

Index(['customerID', 'gender', 'SeniorCitizen', 'Partner', 'Dependents',
       'tenure', 'PhoneService', 'MultipleLines', 'InternetService',
       'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport',
       'StreamingTV', 'StreamingMovies', 'Contract', 'PaperlessBilling',
       'PaymentMethod', 'MonthlyCharges', 'TotalCharges', 'Churn'],
      dtype='object')

In [40]:
df.dtypes

customerID           object
gender               object
SeniorCitizen         int64
Partner              object
Dependents           object
tenure                int64
PhoneService         object
MultipleLines        object
InternetService      object
OnlineSecurity       object
OnlineBackup         object
DeviceProtection     object
TechSupport          object
StreamingTV          object
StreamingMovies      object
Contract             object
PaperlessBilling     object
PaymentMethod        object
MonthlyCharges      float64
TotalCharges         object
Churn                object
dtype: object

In [70]:
is_na_default = df.isna().sum()
is_na_default.name = "is_na_default"

is_na_space = df.astype(str).map(lambda x: x == "" or x == " ").sum()
is_na_space.name = "is_na_space"

pd.concat([is_na_default, is_na_space], axis = 1)

                  is_na_default  is_na_space
customerID                    0            0
gender                        0            0
SeniorCitizen                 0            0
Partner                       0            0
Dependents                    0            0
tenure                        0            0
PhoneService                  0            0
MultipleLines                 0            0
InternetService               0            0
OnlineSecurity                0            0
OnlineBackup                  0            0
DeviceProtection              0            0
TechSupport                   0            0
StreamingTV                   0            0
StreamingMovies               0            0
Contract                      0            0
PaperlessBilling              0            0
PaymentMethod                 0            0
MonthlyCharges                0            0
TotalCharges                  0           11
Churn                         0            0

In [24]:
df.duplicated().sum()

np.int64(0)

## Data preparation (basic)

In [57]:
to_bool_columns = (
    ["SeniorCitizen", "Partner", "Dependents", 
     "PhoneService", "OnlineSecurity", "OnlineBackup", 
     "DeviceProtection", "TechSupport", "StreamingTV", 
     "StreamingMovies", "PaperlessBilling", "Churn"])

for columnn in to_bool_columns:
    df[columnn] = df[columnn].astype(bool)

In [58]:
df.dtypes

customerID           object
gender               object
SeniorCitizen          bool
Partner                bool
Dependents             bool
tenure                int64
PhoneService           bool
MultipleLines        object
InternetService      object
OnlineSecurity         bool
OnlineBackup           bool
DeviceProtection       bool
TechSupport            bool
StreamingTV            bool
StreamingMovies        bool
Contract             object
PaperlessBilling       bool
PaymentMethod        object
MonthlyCharges      float64
TotalCharges         object
Churn                  bool
dtype: object

In [ ]:
df["TotalCharges"]  = pd.to_numeric(df['TotalCharges'], errors='coerce')
df.describe()

            tenure  MonthlyCharges  TotalCharges
count  7043.000000     7043.000000   7032.000000
mean     32.371149       64.761692   2283.300441
std      24.559481       30.090047   2266.771362
min       0.000000       18.250000     18.800000
25%       9.000000       35.500000    401.450000
50%      29.000000       70.350000   1397.475000
75%      55.000000       89.850000   3794.737500
max      72.000000      118.750000   8684.800000